export const SET_TURNS = "SET_TURNS";
export const USER_SUBMIT = "USER_SUBMIT";

export const ADD_USER_MOVE_HISTORY = "ADD_USER_MOVE_HISTORY";

export const SET_MASTERMIND_CODE = "SET_MASTERMIND_CODE";

export const WINNER = "WINNER";

export const SET_DIFFICULTY = "SET_DIFFICULTY";
export const SET_SINGLE_PLAYER = "SET_SINGLE_PLAYER";
export const SET_PVP = "SET_PVP";
export const SET_TOURNAMENT = "SET_TOURNAMENT";
export const TRY_MATCHMAKING = "TRY_MATCHMAKING";
export const FINISH_MATCHMAKING = "FINISH_MATCHMAKING";
export const UPDATE_OPPONENT = "UPDATE_OPPONENT";
export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const SAVE_COMPLETE = "SAVE_COMPLETE";
export const UNABLE_TO_SAVE = "UNABLE_TO_SAVE";
export const SET_WIN_TIME = "SET_WIN_TIME";
export const USER_FOUND = "USER_FOUND";
export const UNABLE_TO_FIND_USER = "UNABLE_TO_FIND_USER";
export const PLAY_GAME = "PLAY_GAME";
export const DISPLAY_USER = "DISPLAY_USER";
export const VIEW_LEADERBOARD = "VIEW_LEADERBOARD";
export const REQUEST_LOGIN = "REQUEST_LOGIN";
export const REQUEST_ACCOUNT_CREATE = "REQUEST_ACCOUNT_CREATE";
export const DISPLAY_CURRENT_USER = "DISPLAY_CURRENT_USER";
export const SELECT_DIFFICULTY = "SELECT_DIFFICULTY";
export const SHOW_LOGIN = "SHOW_LOGIN";
export const HIDE_LOGIN = "HIDE_LOGIN";
export const RESET = "RESET";
export const LOSER = "LOSER";
